/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.miya.twit.utils;

import com.miya.twit.enums.Polarity;
import com.miya.twit.pajo.Expressions;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

/**
 *
 * @author SBT
 */
public class DataInitializer {

    public List<Expressions> getExpressionList() {
        List<Expressions> listExpression = new ArrayList<Expressions>();
        Expressions exp = null;
        for (int i = 0; i < arrExpressions.length; i++) {
            exp = new Expressions();
            exp.setExpression(arrExpressions[i].toLowerCase());
            if (i < 254) {
                exp.setPolarity(Polarity.Negative);
            } else {
                exp.setPolarity(Polarity.Positive);
            }
            exp.setWordForWord(new ArrayList<String>(Arrays.asList(arrExpressions[i].split(" "))));
            listExpression.add(exp);
        }
        return listExpression;
    }

    public static String[] arrExpressions = new String[]{
        "aba altından değnek göstermek",  //Negative
        "abuk sabuk konuşmak",
        "aceleye gelmek",
        "aceleye getirmek",
        "acı çekmek",
        "aç susuz",
        "aç susuz kalmak",
        "açık saçık",
        "açık seçik",
        "açıkta kalmak",
        "açlıktan nefesi kokmak",
        "adı batasıca",
        "adı batmak",
        "adı çıkmak",
        "adı karışmak",
        "adı sanı belirsiz",
        "aforoz etmek",
        "afyonu başına vurmak",
        "afyonunu patlatmak",
        "ağır hasta",
        "ağız dalaşı",
        "ağız değiştirmek",
        "ağız kalabalığı",
        "ağza almamak",
        "ağzı bozuk",
        "ağzı gevşek",
        "ağzı pis",
        "ağzına sıçmak",
        "ağzının tadı bozulmak",
        "ağzının tadı kaçmak",
        "ağzımın tadı bozulmak",
        "ağzımın tadı kaçmak",
        "ahı gitmiş, vahi kalmış",
        "ahı gitmiş,vahi kalmış",
        "ahı gitmiş vahi kalmış",
        "ahı tutmak",
        "akıl kârı olmamak",
        "akıl kârı değil",
        "aklı başında olmamak",
        "aklı başında değil",
        "aklım başımda olmamak",
        "aklım başımda değil",
        "aklını almak",
        "aklını bozmak",
        "aklını çelmek",
        "aklımı çelmek",
        "aklını peynir ekmekle yemek",
        "alaşağı etmek",
        "ali cengiz oyunu",
        "alicengiz oyunu",
        "allah'ın belası",
        "allahın belası",
        "allah'ın cezası",
        "allahın cezası",
        "allak bullak",
        "allak bullak etmek",
        "ana avrat dümdüz gitmek",
        "anasını ağlatmak",
        "anasını bellemek",
        "anasının gözü",
        "arap saçına dönmek",
        "at izi it izine karışmak",
        "attan inip eşeğe binmek",
        "avucunu yalamak",
        "ayağına dolaşmak",
        "bağrını delmek",
        "bahtı kara",
        "baldırı çıplak",
        "baltayı taşa vurmak",
        "baskin yemek",
        "baskin yedik",
        "bastığı yerde ot bitmemek",
        "baş ağrısı",
        "baş belâsı",
        "baş belası",
        "baş kaldırmak",
        "burnundan gelmek",
        "burnumdan gelmek",
        "burnundan solumak",
        "burnumdan solumak",
        "burnunu kırmak",
        "burnumu kırmak",
        "boynu altında kalsın",
        "burnundan gelmek",
        "burnundan solumak",
        "büyüklük göstermek",
        "can evinden vurmak",
        "canını almak",
        "canını sıkmak",
        "canımı sıkmak",
        "ciğeri beş para etmemek",
        "ciğerini sökmek",
        "çenesi düşük",
        "çocuk aldırmak",
        "çocuk düşürmek",
        "çürük çarık",
        "çiğ süt emmiş",
        "çile çekmek",
        "dalavere çevirmek",
        "defterden silmek",
        "delik deşik",
        "dümen çevirmek",
        "düşük yapmak",
        "eceline susamak",
        "eğri büğrü",
        "evlat acısı gibi içine çökmek",
        "faka basmak",
        "fena gözle bakmak",
        "fena olmak",
        "fena oldu",
        "fena yapmak",
        "fırıldak çevirmek",
        "fitne fücur",
        "fitne sokmak",
        "gına gelmek",
        "günah işlemek",
        "günaha girmek",
        "günahını çekmek",
        "günahını vermez",
        "haddini bilmek",
        "hafakanlar basmak",
        "hakkını yemek",
        "hali harap olmak",
         "hali harap oldu",
        "hapı yutmak",
        "har vurup harman savurmak",
        "haraca bağlamak",
        "haraca kesmek",
        "haram olmak",
        "haram oldu",
        "haram para",
        "hor görmek",
        "hor kullanmak",
        "hüküm giymek",
        "hüküm sürmek",
        "ırzına geçmek",
        "içinden pazarlıklı",
        "içine etmek",
        "içini bayıltmak",
        "içini kurt yemek",
        "içler acısı",
        "kaba saba",
        "kabir azabı çekmek",
        "kafayı vurmak",
        "kafasını vurmak",
        "kalayı basmak",
        "kalbini kırmak",
        "kalbimi kırmak",
        "kan ağlamak",
        "kumpas kurmak",
        "kurşuna dizmek",
        "kuyruk acısı",
        "kuyusunu kazmak",
        "küçük düşmek",
        "küçük görmek",
        "laf atmak",
        "laf söyledi balkabağı",
        "leş gibi kokmak",
        "leşini sermek",
        "madik atmak",
        "mahallebi çocuğu",
        "muhallebi çocuğu",
        "mahkemelik olmak",
        "mahkemelik oldu",
        "mahkemeye düşmek",
        "malın gözü",
        "mayası bozuk",
        "maytap geçmek",
        "meydan dayağı",
        "mezardan çıkarmak",
        "mezarını kazmak",
        "midesi bulanmak",
        "muşmula suratlı",
        "namus belası",
        "nazar değmek",
        "nazara gelmek",
        "niyeti bozuk",
        "numara yapmak",
        "ocağım söndürmek",
        "ocağın söndürmek",
        "ocağımız söndürmek",
        "ocağına incir dikmek",
        "ocağına incir ağacı dikmek",
        "ocağıma incir ağacı dikmek",
        "oyuna gelmek",
        "oyunbozanlık yapmak",
        "oyun bozanlık yapmak",
        "oyunbozanlık etmek",
        "oyun bozanlık etmek",
        "öbür dünyayı boylamak",
        "ödü patlamak",
        "ödüm patlamak",
        "ölçüyü kaçırmak",
        "ömrün çürütmek",
        "ömrümüz çürütmek",
        "ömrüm çürütmek",
        "ömür törpüsü",
        "örtbas etmek",
        "özrü kabahatinden büyük",
        "paçayı kaptırmak",
        "paniğe kapılmak",
        "parmağında oynatmak",
        "patlak vermek",
        "peşkeş çakmek",
        "pislik götürmek",
        "pişmiş aşa su katmak",
        "pot kırmak",
        "pusu kurmak",
        "pusuya düşmek",
        "rahat yüzü görmemek",
        "rezalet çıkarmak",
        "saçı uzun aklı kısa",
        "saçma sapan",
        "sürgüne göndermek",
        "sütü bozuk",
        "şah iken şahbaz olmak",
        "şah iken şahbaz oldu",
        "şamar oğlanı",
        "şapa oturmak",
        "şeytan görsün yüzünü",
        "şeytana uymak",
        "şom ağızlı",
        "tadını kaçırmak",
        "tahtası eksik",
        "taş bebek gibi",
        "tımarhane kaçkını",
        "Tongaya düşmek",
        "Tüyü bozuk",
        "Ucunu kaçırmak",
        "utancından yere girmek",
        "uygunsuz kadın",
        "Üç bucuk atmak",
        "Üstü başı dökülmek",
        "Üstüne gül koklamak",
        "üstüne yatmak",
        "üstüne yıkmak",
        "Üzüm üzüm üzülmek",
        "vurgun yemek",
        "yağcılık etmek",
        "yağcılık yapmak",
        "yakasına yapışmak",
        "yakayı ele vermek",
        "yalan dolan",
        "yalan yanlış",
        "yan çizmek",
        "yangına körükle gitmek",
        "yüzünü ekşitmek",
        "yüzünü kızarttı",
        "yüzümü kızarttı",
        "yüzümüzü kızarttı",
        "zar tutmak",
        "zehir etmek",
        "zehir zemberek",
        "Zehir zıkkım olsun",
        "zemzem kuyusuna işemek",
        "Zıddına gitmek",
        "Ziftin pekini yesin",
        "Zihnim çelmek",
        "zihnini bulandırmak",
        "zindan oldu",
        "zindan olmak",
        "ziyan etmek",
        "abayı yakmak", /////Positive
        "abdest tazelemek",
        "acısını çıkarmak",
        "alnım açık",
        "alnı açık",
        "açık kalpli",
        "açık yürekli",
        "adam olmak",
        "adam oldu",
        "adama benzemek",
        "adamdan saymak",
        "adamını bulmak",
        "adamlık sende kalsın",
        "insanlık sende kalsın",
        "ağır adam",
        "ağır başlı",
        "ağzına layık",
        "ağzına lâyık",
        "akan sular durmak",
        "akıllı uslu",
        "aklı başında",
        "aklı çıkmak",
        "aklını başından almak",
        "alımı çalımı yerinde",
        "alın teri dökmek",
        "anası onu kadir gecesi doğurmuş",
        "anası kadir gecesi doğurmuş",
        "aslan yürekli",
        "ayağın uğurlu",
        "ayağım uğurlu",
        "ayakta kalmak",
        "baba adam",
        "baskın yapmak",
        "baş tacı etmek",
        "başımın üstünde yeri var",
        "başımızın üstünde yeri var",
        "büyüklük göstermek",
        "burcu burcu kokmak",
        "cana yakın",
        "ciğerimin köşesi",
        "çakı gibi",
        "çenesi kuvvetli",
        "çoluk çocuğa karışmak",
        "düşman çatlatmak",
        "ekmeğini taştan çıkarmak",
        "el sıkışmak",
        "fit olmak",
        "fit oldu",
        "fukara babası",
        "göbek atmak",
        "güler yüz",
        "hal hatır sormak",
        "hali vakti yerinde",
        "hanım hanımcık",
        "hık demiş burnundan düşmüş",
        "hızır gibi yetişmek",
        "içi dışı bir",
        "kadir gecesi doğmuş",
        "kafa dengi",
        "kafası çalışmak",
        "kalp kazanmak",
        "kurtlarını dökmek",
        "kurtlarımı dökmek",
        "kurtlarımızı dökmek",
        "kuş sütüyle beslemek",
        "makbule geçmek",
        "muradına ermek",
        "mürekkep yalamış",
        "müslüman adam",
        "mürüvvetini görmek",
        "nefsini yenmek",
        "nikah kıymak",
        "omuzda taşımak",
        "ölmek var, dönmek yok",
        "ölmek var dönmek yok",
        "ömür adam",
        "örnek almak",
        "özen göstermek",
        "özü sözü bir",
        "paçayı kurtarmak",
        "parmakla gösterilmek",
        "paşa gibi yaşamak",
        "puan almak",
        "rahatına bakmak",
        "rast gelmek",
        "rayına gitmek",
        "rayına oturmak",
        "rekor kırmak",
        "renk katmak",
        "safa atmak",
        "safa bulduk",
        "safa geldiniz",
        "sahip çıkmak",
        "sürüsüne bereket",
        "şaha kalkmak",
        "şeytanın ayağını kırmak",
        "taburcu olmak",
        "taburcu oldu",
        "tadına varmak",
        "tadını çıkarmak",
        "tatlı bela",
        "tok gözlü",
        "tur atlamak",
        "ucuz atlatmak",
        "ün kazanmak",
        "ün salmak",
        "üstesinden gelmek",
        "üstün gelmek",
        "üstüne titremek",
        "Verilmiş sadakamız varmış",
        "yakınlık duymak",
        "yüzünü güldürmek",
        "zevk almak",
        "zihin açıklığı",
        "ziyade olsun",
        "ziyafet çekmek"
    };
}
